[project]
name = "hsi-utils"
version = "0.1.0"
description = "Shared utility library"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.9.4",
    "numpy>=2.0.2",
    "omegaconf>=2.3.0",
    "rich>=14.2.0",
]
